"""add new fields

Revision ID: 48f5c0f9a99d
Revises: ebd8b2abce4d
Create Date: 2025-10-27 19:28:20.750548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f5c0f9a99d'
down_revision = 'ebd8b2abce4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('shipping_floor', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('shipping_zipcode', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('shipping_region', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('shipping_region')
        batch_op.drop_column('shipping_zipcode')
        batch_op.drop_column('shipping_floor')
        batch_op.drop_column('shipping_phone')

    # ### end Alembic commands ###
