"""change user table

Revision ID: ee53204760ae
Revises: 40d5f7970cd5
Create Date: 2025-10-28 18:14:55.627241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee53204760ae'
down_revision = '40d5f7970cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
